steps:
## Building the container image from the Dockerfile in the local
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcp-devops-project-main", "."]
## Pushing the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcp-devops-project-main"]
options:
  logging: CLOUD_LOGGING_ONLY
