apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: gcp
  name: gcp-devops-gke-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  strategy: {}
  template:
    metadata:
      
      labels:
        app: gcp
    spec:
      containers:
      - image: gcp-devops-project-prod/composed-sensor-435108-i6/gcp-devops-project:latest
        name: gcp-devops-project-container
        ports:
         - containerPort: 5000
        env:
         - name: PORT
           value: "5000"
        resources: {}

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "gcp-devops-gke-service"
  namespace: "gcp-devops-dev" 
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec: 
  ports: 
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector: 
    app: "gcp"
  type: "LoadBalancer"
        

